name: GitHub Actions CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ci-cd-requirements.txt

      - name: Check style
        run: |
          make check-style

      - name: Check types
        run: |
          make check-type

      - name: Run unit tests
        run: |
          make run-test

      - name: Run program tests
        run: |
          make program-test
